name: fast_trivia
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  equatable: ^2.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:  
  uses-material-design: true

  assets:
    - assets/gif/